# Generated by Django 4.1.7 on 2023-03-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type1', models.CharField(max_length=10)),
                ('type2', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('imgfile', models.ImageField(blank=True, null=True, upload_to='')),
                ('details', models.CharField(default='', max_length=200)),
                ('season', models.CharField(max_length=50)),
            ],
        ),
    ]
