# Generated by Django 4.1.7 on 2023-04-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='style',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='스타일'),
        ),
    ]
