# Generated by Django 4.1.7 on 2023-03-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='키'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], null=True, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='몸무게'),
        ),
    ]
