# Generated by Django 4.2 on 2023-05-05 16:30

from django.db import migrations, models
import django.utils.timezone
import muapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='viton_upload_cloth',
            fields=[
                ('clothesname', models.CharField(default='sample', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('image', muapp.models.ResizedImageField(upload_to='datasets/cloth')),
                ('uploadUser', models.CharField(max_length=30)),
                ('uploadDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-uploadDate'],
            },
        ),
        migrations.CreateModel(
            name='viton_upload_model',
            fields=[
                ('clothesname', models.CharField(default='sample', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('image', muapp.models.ResizedImageField(upload_to='datasets/model')),
                ('uploadUser', models.CharField(max_length=30)),
                ('uploadDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-uploadDate'],
            },
        ),
        migrations.CreateModel(
            name='viton_upload_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', muapp.models.ResizedImageField(upload_to='datasets/results')),
                ('uploadUser', models.CharField(default='sample', max_length=50)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
