# Generated by Django 4.1.7 on 2023-03-31 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesGroup',
            fields=[
                ('groupID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('clothesObject', models.ManyToManyField(related_name='groups', to='muapp.clothes')),
            ],
        ),
        migrations.AddField(
            model_name='clothes',
            name='group',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='muapp.clothesgroup'),
        ),
    ]
