# Generated by Django 4.1.7 on 2023-03-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='upload_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='imgfiles/%m'),
        ),
    ]
