# Generated by Django 4.1.7 on 2023-03-24 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='uploadUser',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
