# Generated by Django 4.2 on 2023-04-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viton_upload_cloth",
            name="image",
            field=models.ImageField(upload_to="datasets/cloth"),
        ),
        migrations.AlterField(
            model_name="viton_upload_model",
            name="image",
            field=models.ImageField(upload_to="datasets/image"),
        ),
        migrations.AlterField(
            model_name="viton_upload_result",
            name="image",
            field=models.ImageField(upload_to="datasets/results"),
        ),
    ]
