# Generated by Django 4.1.7 on 2023-04-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musinsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.TextField()),
                ('item_title', models.TextField()),
                ('item_model', models.TextField()),
                ('item_picture', models.URLField()),
                ('item_page', models.URLField()),
            ],
            options={
                'db_table': 'musinsa',
            },
        ),
    ]
