# Generated by Django 4.1.7 on 2023-03-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='groupID',
            field=models.IntegerField(default=0),
        ),
    ]
