# Generated by Django 4.1.7 on 2023-03-24 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0002_clothes_uploaduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='uploadUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
