# Generated by Django 4.1.7 on 2023-04-02 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0002_musinsa'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='musinsa',
            table=None,
        ),
    ]
