# Generated by Django 4.1.7 on 2023-03-31 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0002_clothesgroup_clothes_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='clothesTest',
            fields=[
                ('uploadUserName', models.CharField(default='unknown', max_length=30)),
                ('type1', models.CharField(max_length=10)),
                ('type2', models.CharField(max_length=50)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=50)),
                ('details', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('groupID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('uploadUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='photos',
            fields=[
                ('photoID', models.AutoField(primary_key=True, serialize=False)),
                ('imgfile', models.ImageField(blank=True, default='imgfiles/no_image.png', null=True, upload_to='imgfiles/%m/%d')),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muapp.clothestest')),
            ],
        ),
    ]
