# Generated by Django 4.1.7 on 2023-03-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0002_clothes_upload_date_alter_clothes_imgfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AlterField(
            model_name='clothes',
            name='imgfile',
            field=models.ImageField(blank=True, default='imgfiles/no_image.png', null=True, upload_to='imgfiles/%m'),
        ),
    ]
