# Generated by Django 4.1.7 on 2023-03-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0002_alter_user_height_alter_user_sex_alter_user_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, '남자'), (1, '여자')], null=True, verbose_name='성별'),
        ),
    ]
