# Generated by Django 4.1.7 on 2023-03-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0003_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('남', '남자'), ('여', '여자')], max_length=1, null=True, verbose_name='성별'),
        ),
    ]
