# Generated by Django 4.1.7 on 2023-03-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0003_alter_clothes_options_alter_clothes_imgfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={},
        ),
    ]
