# Generated by Django 4.2 on 2023-05-06 21:41

from django.db import migrations
import muapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0003_viton_upload_result_cloth_viton_upload_result_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viton_upload_cloth',
            options={'ordering': ['-ID']},
        ),
        migrations.AlterModelOptions(
            name='viton_upload_model',
            options={'ordering': ['-ID']},
        ),
        migrations.AlterField(
            model_name='viton_upload_cloth',
            name='image',
            field=muapp.models.ResizedImageField(upload_to=muapp.models.random_name_C),
        ),
        migrations.AlterField(
            model_name='viton_upload_model',
            name='image',
            field=muapp.models.ResizedImageField(upload_to=muapp.models.random_name_M),
        ),
    ]
