# Generated by Django 4.1.7 on 2023-03-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0003_clothes_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='groupID',
            field=models.CharField(default='0000', max_length=10, unique=True),
        ),
        migrations.AddConstraint(
            model_name='clothes',
            constraint=models.UniqueConstraint(fields=('id', 'groupID'), name='Unique groupID'),
        ),
    ]
