# Generated by Django 4.1.7 on 2023-03-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0003_alter_clothes_uploaduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='uploadUserName',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
