# Generated by Django 4.2 on 2023-04-28 17:16

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0003_alter_viton_upload_result_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viton_upload_cloth',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[768, 1024], upload_to='datasets/cloth'),
        ),
        migrations.AlterField(
            model_name='viton_upload_model',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[768, 1024], upload_to='datasets/image'),
        ),
    ]
