# Generated by Django 4.1.7 on 2023-03-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0004_alter_clothes_groupid_clothes_unique groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='groupID',
            field=models.CharField(max_length=10),
        ),
    ]
