# Generated by Django 4.1.7 on 2023-04-14 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0004_alter_clothes_ucodi'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
