# Generated by Django 4.1.7 on 2023-04-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0004_remove_clothestest_uploaduser_remove_clothes_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
