# Generated by Django 4.1.7 on 2023-03-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0004_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='성별'),
        ),
    ]
