# Generated by Django 4.2 on 2023-05-08 15:13

from django.db import migrations, models
import muapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0004_alter_viton_upload_cloth_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viton_upload_cloth',
            name='maskimage',
            field=muapp.models.ResizedImageField(blank=True, null=True, upload_to='datasets/cloth-mask'),
        ),
        migrations.AddField(
            model_name='viton_upload_model',
            name='maskmodel',
            field=muapp.models.ResizedImageField(blank=True, null=True, upload_to='datasets/image-parse'),
        ),
        migrations.AddField(
            model_name='viton_upload_model',
            name='openposeImage',
            field=muapp.models.ResizedImageField(blank=True, null=True, upload_to='datasets/openpose-parse'),
        ),
        migrations.AddField(
            model_name='viton_upload_model',
            name='openposeJson',
            field=models.FileField(blank=True, null=True, upload_to='datasets/openpose-json'),
        ),
    ]
