# Generated by Django 4.2 on 2023-04-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0005_alter_viton_upload_result_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viton_upload_cloth',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='viton_upload_model',
            options={'ordering': ['-id']},
        ),
    ]
