# Generated by Django 4.2 on 2023-05-09 17:48

from django.db import migrations
import muapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0005_viton_upload_cloth_maskimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viton_upload_model',
            name='openposeImage',
            field=muapp.models.ResizedImageField(blank=True, null=True, upload_to='datasets/openpose-img'),
        ),
    ]
