# Generated by Django 4.1.7 on 2023-03-17 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0005_alter_clothes_options_alter_clothes_details_and_more'),
        ('muapp', '0005_alter_clothes_options_remove_clothes_season_and_more'),
    ]

    operations = [
    ]
