# Generated by Django 4.1.7 on 2023-04-01 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0005_photos_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='count',
        ),
    ]
