# Generated by Django 4.1.7 on 2023-03-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0005_alter_clothes_groupid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clothes',
            name='Unique groupID',
        ),
    ]
