# Generated by Django 4.1.7 on 2023-04-16 02:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0005_clothes_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='musinsa',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes2', to=settings.AUTH_USER_MODEL),
        ),
    ]
