# Generated by Django 4.1.7 on 2023-03-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0006_merge_20230318_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
