# Generated by Django 4.1.7 on 2023-04-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0006_musinsa_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='viton_upload_cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes_name', models.CharField(max_length=50)),
                ('clothes_image', models.FileField(upload_to='datasets/cloth')),
            ],
        ),
        migrations.CreateModel(
            name='viton_upload_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('model_image', models.FileField(upload_to='datasets/image')),
            ],
        ),
    ]
