# Generated by Django 4.1.7 on 2023-04-01 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0002_user_style'),
        ('muapp', '0006_remove_photos_count'),
    ]

    operations = [
    ]
