# Generated by Django 4.1.7 on 2023-03-26 03:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0006_remove_clothes_unique groupid'),
    ]

    operations = [
        migrations.CreateModel(
            name='imgFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgfile', models.ImageField(blank=True, default='imgfiles/no_image.png', null=True, upload_to='imgfiles/%m/%d')),
                ('groupID', models.IntegerField()),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
