# Generated by Django 4.2 on 2023-05-03 22:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import muapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0006_alter_viton_upload_cloth_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viton_upload_cloth',
            options={'ordering': ['-uploadDate']},
        ),
        migrations.AlterModelOptions(
            name='viton_upload_model',
            options={'ordering': ['-uploadDate']},
        ),
        migrations.RemoveField(
            model_name='viton_upload_cloth',
            name='id',
        ),
        migrations.RemoveField(
            model_name='viton_upload_model',
            name='id',
        ),
        migrations.AddField(
            model_name='viton_upload_cloth',
            name='uploadDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='viton_upload_model',
            name='uploadDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='viton_upload_result',
            name='cloth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='muapp.viton_upload_cloth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viton_upload_result',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='muapp.viton_upload_model'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viton_upload_cloth',
            name='image',
            field=muapp.models.ResizedImageField(upload_to='datasets/cloth'),
        ),
        migrations.AlterField(
            model_name='viton_upload_cloth',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='viton_upload_cloth',
            name='uploadUser',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='viton_upload_model',
            name='image',
            field=muapp.models.ResizedImageField(upload_to='datasets/image'),
        ),
        migrations.AlterField(
            model_name='viton_upload_model',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='viton_upload_result',
            name='image',
            field=muapp.models.ResizedImageField(upload_to='datasets/results'),
        ),
        migrations.AlterField(
            model_name='viton_upload_result',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
