# Generated by Django 4.1.7 on 2023-03-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0007_alter_clothes_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='username',
            field=models.CharField(default='unknown', max_length=15, verbose_name='username'),
        ),
    ]
