# Generated by Django 4.1.7 on 2023-04-22 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0007_viton_upload_cloth_viton_upload_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viton_upload_cloth',
            old_name='clothes_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='viton_upload_cloth',
            old_name='clothes_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='viton_upload_model',
            old_name='model_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='viton_upload_model',
            old_name='model_name',
            new_name='name',
        ),
    ]
