# Generated by Django 4.1.7 on 2023-04-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0007_merge_0002_user_style_0006_remove_photos_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='contentType',
            field=models.CharField(default='image/jpeg', max_length=20),
        ),
    ]
