# Generated by Django 4.2 on 2023-05-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0007_alter_viton_upload_cloth_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viton_upload_cloth',
            old_name='name',
            new_name='filename',
        ),
        migrations.AddField(
            model_name='viton_upload_cloth',
            name='clothesname',
            field=models.CharField(default='sample', max_length=100),
        ),
    ]
