# Generated by Django 4.1.7 on 2023-03-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0008_clothes_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='imgfileTest',
            field=models.FileField(blank=True, default='imgfiles/no_image.png', null=True, upload_to='imgfiles/%m/%d'),
        ),
    ]
