# Generated by Django 4.2 on 2023-05-03 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0008_rename_name_viton_upload_cloth_filename_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viton_upload_cloth',
            old_name='filename',
            new_name='name',
        ),
    ]
