# Generated by Django 4.1.7 on 2023-03-22 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0009_clothes_imgfiletest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='imgfileTest',
        ),
    ]
