# Generated by Django 4.1.7 on 2023-03-26 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muapp', '0009_imgfiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imgFiles',
        ),
    ]
